name: Deploy
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fail early if secret missing
        if: ${{ secrets.DISCORD_WEBHOOK == '' }}
        run: |
          echo "‚ùå DISCORD_WEBHOOK saknas eller √§r tom."
          exit 1

      - name: Send message (appleboy)
        if: ${{ secrets.DISCORD_WEBHOOK != '' }}
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          message: "üöÄ ${{ github.repository }} has been successfully deployed by ${{ github.actor }}."

